name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # Позволяет запускать сборку вручную для теста

jobs:
  # 1. СНАЧАЛА СОБИРАЕМ НА ВСЕХ ОС
  build:
    strategy:
      matrix:
        include:
      - os: ubuntu-latest
        artifact_name: build-Linux
        ext: ".bin"
        out_name: DiSiT.bin

      - os: windows-latest
        artifact_name: build-Windows
        ext: ".exe"
        out_name: DiSiT.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          pip install nuitka customtkinter

      - name: Build
        run: |
          python -m nuitka --onefile --follow-imports --assume-yes-for-downloads start.py --output-filename=DiSiT${{ matrix.ext }}

      # Загружаем собранные бинарники как артефакты
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            DiSiT${{ matrix.ext }}

  # 2. ПОТОМ ПУБЛИКУЕМ РЕЛИЗ
  release:
    needs: build # Ждем, пока завершится джоба сборки
    runs-on: ubuntu-latest
    
    # Решаем ошибку 403 (выдаем права на запись релиза)
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Скачиваем ВСЕ артефакты из джобы build
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # Перемещаем скрипт .py в корень для релиза (так как checkout чистый)
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifacts/build-Linux/DiSiT
            artifacts/build-Linux/DiSiT.bin
            artifacts/build-Windows/DiSiT.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
